### ISSUE TITLE
online dictionary helper与longman6

### ISSUE THREAD

**Issue by techlarry** [ninja33/mdx-server#11]
我是用了online dictionary helper，词典是 朗文6，脚本是helper里面自带的，发现不能取词。然后进入helper的调试界面，有很多错误。

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'indexOf')
    at encn_LDOCE6MDX.findLDOCE6 (eval at backend_loadScript (sandbox.js:39:26), <anonymous>:85:26)
    at async Promise.all (index 0)
    at async encn_LDOCE6MDX.findTerm (eval at backend_loadScript (sandbox.js:39:26), <anonymous>:34:23)
    at async Sandbox.backend_findTerm (sandbox.js:74:25)

**Comment by wangxinyu6666** [comment]
这单码都是4年前的了。
